### ISSUE TITLE
Possible PR to upstream container

### ISSUE THREAD

**Issue by IronicBadger** [jwigley/docker-smokeping-speedtest#1]
Hi,

Would you consider making this a PR to the upstream Linuxserver smokeping container? I'd rather you got the credit :)

Thanks!

**Comment by jwigley** [comment]
Thanks for the opportunity, sorry I'm super late replying. For some reason I wasn't "watching" my own repos and only just saw this now!

Interesting discussions in that thread around the perf results under docker. Guessing I haven't ran into it myself because my internet is pretty terrible. I'll close this for now, but will consider an upstream PR in the future. 

Thanks!
