### ISSUE TITLE
Feature request - Probe SSH

### ISSUE THREAD

**Issue by c3c1** [jwigley/docker-smokeping-speedtest#23]
Just wondering if you might take on the improvement of SSH.pm which is currently broken in the linuxserver image. 
The current image contains the probe SSH, but needs a tweak. The problem was discovered some time ago according to a debian report in 2019, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=946852. The use of rsa1 caused prevents smokeping from starting.

That fix leaves one more issue when using the linuxserver image. That image does not support ssh, and to start the probe tests against 127.0.0.1 (same line as the rsa1 reference). There are various solution to that, add enable ssh, change the 127.0.0.1, or other change to the test.

I did put this to the linuxserver team, but no response yet.

Thoughts?

**Comment by jwigley** [comment]
I'll try and look into this and hopefully implement something when I can. I think the only tricky bit will be installing and running ssh in the linuxserver standard way.

Ideally it would be fixed in the linuxserver image though, but it doesn't look like there's much activity there for the smokeping side of things. It seems to be mostly just platform updates.

**Comment by jwigley** [comment]
@c3c1 I decided to go with changing the test rather than adding ssh to the container. 

Here's the built image of the changes in https://github.com/jwigley/docker-smokeping-speedtest/pull/24 if you want to give it a go:
```
docker pull jwigley/smokeping-speedtest:ssh-probe
```

**Comment by c3c1** [comment]
tested, works
